platform :ios, '8.0'
inhibit_all_warnings!


target 'ulucuAutoPatrolShop'  do
    project '../ulucuAutoPatrolShop/ulucuAutoPatrolShop'
end

target 'OneApplication’ do
    project 'OneApplication'
    pod 'Mycategory', :path => '../Mycategory'
    pod ‘Server’, :path => '../Server'
    pod 'Module', :path => '../Module'

end
