platform :ios, '8.0'
use_frameworks!



target 'OneApplication' do
    project 'OneApplication'
    pod 'Mycategory', :path => '../Mycategory'
    pod 'Server', :path => '../Server'
    pod 'Module', :path => '../Module'
end
