platform :ios, '8.0'
inhibit_all_warnings!


workspace 'MyWorkspace'

target 'CocoapodsDemo'  do
    project 'CocoapodsDemo/CocoapodsDemo'

end

target 'Demo1Framework' do
    project 'Demo1Framework/Demo1Framework'

end

target 'Demo2Framework' do
    project 'Demo2Framework/Demo2Framework'

end

target 'Demo1Bundle' do
    project 'Demo1Framework/Demo1Framework'
    
end

post_install do |installer|
    names = Array.new
        installer.pods_project.targets.each do |target|
        if !(target.name == "Pods-"+"CocoapodsDemo")
            framework_name = target.name.slice(5,target.name.length)
            names<<framework_name
        end
    end
    puts names
    File.open("Build-framework.feng", "w") do |aFile|
        content=""
        names.each do |name|
            content += name+"\n"
        end
        content.chop!
        aFile.syswrite(content)
    end
end
