platform :ios, '8.0'
inhibit_all_warnings!


abstract_target 'TargetSetting' do
    pod 'AFNetworking', :path => '../master/AFNetworking-master'
    pod 'Mycategory', :path => '../Mycategory'
    pod 'MBProgressHUD', :path => '../master/MBProgressHUD-master'
    pod 'SDWebImage', :path => '../master/SDWebImage-master'
    
    target 'Demo' do
        pod 'Module', :path => '../Module'
    end
    
end
